In [70]:
import pandas as pd 
import numpy as np

In [71]:
books= pd.read_csv(r'C:\Users\tilum\OneDrive\Desktop\books.csv')
users = pd.read_csv(r'C:\Users\tilum\OneDrive\Desktop\users.csv')
ratings = pd.read_csv(r'C:\Users\tilum\OneDrive\Desktop\ratings.csv')

C:\Users\tilum\AppData\Local\Temp\ipykernel_21296\2406617115.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books= pd.read_csv(r'C:\Users\tilum\OneDrive\Desktop\books.csv')

In [72]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [73]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [74]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726   155061224            5
2   276727   446520802            0
3   276729  052165615X            3
4   276729   521795028            6

In [75]:
books.duplicated().sum()

0

In [76]:
ratings.duplicated().sum()

72

In [77]:
users.duplicated().sum()

0

Popularity based RS

In [19]:
# here we will consider only those books which have got minimum 250 votes/rating

In [78]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1048575 non-null  int64
 1   ISBN         1048575 non-null  object
 2   Book-Rating  1048575 non-null  int64
dtypes: int64(2), object(1)
memory usage: 24.0+ MB

In [79]:
rating_with_name = ratings.merge(books, on= 'ISBN')

In [80]:
rating_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
941107,250764,440106575,0,HIDDEN FIRES,JANETTE RADCLIFFE,1978,Dell,http://images.amazon.com/images/P/0440106575.0...,http://images.amazon.com/images/P/0440106575.0...,http://images.amazon.com/images/P/0440106575.0...
941108,250764,451157516,0,"Cheyenne (Fortunes West, No 2)",A.R. Riefe,1988,New Amer Library (Mm),http://images.amazon.com/images/P/0451157516.0...,http://images.amazon.com/images/P/0451157516.0...,http://images.amazon.com/images/P/0451157516.0...
941109,250764,048623715X,0,Glamorous Movie Stars of the Thirties: Paper D...,Tom Tierney,1982,Dover Publications,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...
941110,250764,486256588,0,Schiaparelli Fashion Review: Paper Dolls in Fu...,Tom Tierney,1988,Dover Publications,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...
941111,250764,515069434,0,Lady Laughing Eyes (To Have and to Hold),Lee Damon,1984,Jove Books,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...

In [27]:
rating_with_name.duplicated().sum()

7

In [83]:
rating_with_name[rating_with_name['Book-Title']=='Ã?Â?rger mit Produkt X. Roman.'].mean()['Book-Rating']

C:\Users\tilum\AppData\Local\Temp\ipykernel_21296\638771196.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  rating_with_name[rating_with_name['Book-Title']=='Ã?Â?rger mit Produkt X. Roman.'].mean()['Book-Rating']

5.25

In [28]:
num_rating_df = rating_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [29]:
num_rating_df

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Beyond IBM: Leadership Marketing and Finance ...            1
4        Clifford Visita El Hospital (Clifford El Gran...            1
...                                                   ...          ...
230215                                 Ã?Â?l- Connection.            1
230216                                      Ã?Â?lpiraten.            2
230217                     Ã?Â?rger mit Produkt X. Roman.            4
230218                              Ã?Â?stlich der Berge.            2
230219                                  Ã?Â?thique en toc            2

[230220 rows x 2 columns]

In [32]:
num_rating_df.rename(columns ={'Book-Rating':'num_ratings'},inplace = True)

In [33]:
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Beyond IBM: Leadership Marketing and Finance ...            1
4        Clifford Visita El Hospital (Clifford El Gran...            1
...                                                   ...          ...
230215                                 Ã?Â?l- Connection.            1
230216                                      Ã?Â?lpiraten.            2
230217                     Ã?Â?rger mit Produkt X. Roman.            4
230218                              Ã?Â?stlich der Berge.            2
230219                                  Ã?Â?thique en toc            2

[230220 rows x 2 columns]

In [81]:
num_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230220 entries, 0 to 230219
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Book-Title   230220 non-null  object
 1   num_ratings  230220 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.5+ MB

In [34]:
rating_with_name['Book-Rating']= pd.to_numeric(rating_with_name['Book-Rating'], errors ='coerce')

In [35]:
# group by book title and calculate the mean of book-rating

In [36]:
avg_rating_df = rating_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()

In [37]:
# Rename the column

In [38]:
avg_rating_df.rename(columns ={'Book-Rating':'avg_rating'}, inplace = True)

In [39]:
# Display the result

In [40]:
print(avg_rating_df)

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...        2.25
1                                   Always Have Popsicles        0.00
2                    Apple Magic (The Collector's series)        0.00
3        Beyond IBM: Leadership Marketing and Finance ...        0.00
4        Clifford Visita El Hospital (Clifford El Gran...        0.00
...                                                   ...         ...
230215                                 Ã?Â?l- Connection.        0.00
230216                                      Ã?Â?lpiraten.        0.00
230217                     Ã?Â?rger mit Produkt X. Roman.        5.25
230218                              Ã?Â?stlich der Berge.        4.00
230219                                  Ã?Â?thique en toc        4.00

[230220 rows x 2 columns]

In [41]:
popular_df = num_rating_df.merge(avg_rating_df, on = 'Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.25
1,Always Have Popsicles,1,0.00
2,Apple Magic (The Collector's series),1,0.00
3,Beyond IBM: Leadership Marketing and Finance ...,1,0.00
4,Clifford Visita El Hospital (Clifford El Gran...,1,0.00
...,...,...,...
230215,Ã?Â?l- Connection.,1,0.00
230216,Ã?Â?lpiraten.,2,0.00
230217,Ã?Â?rger mit Produkt X. Roman.,4,5.25
230218,Ã?Â?stlich der Berge.,2,4.00
230219,Ã?Â?thique en toc,2,4.00

In [43]:
popular_df = popular_df[popular_df['num_ratings']>250].sort_values('avg_rating',ascending = False).head(50)

In [44]:
popular_df

,Book-Title,num_ratings,avg_rating
76831,Harry Potter and the Goblet of Fire (Book 4),346,5.945087
76843,Harry Potter and the Prisoner of Azkaban (Book 3),380,5.884211
76835,Harry Potter and the Order of the Phoenix (Boo...,316,5.544304
76823,Harry Potter and the Chamber of Secrets (Book 2),501,5.177645
182892,The Hobbit : The Enchanting Prelude to The Lor...,261,4.969349
76854,Harry Potter and the Sorcerer's Stone (Harry P...,519,4.938343
178857,The Fellowship of the Ring (The Lord of the Ri...,340,4.885294
209806,To Kill a Mockingbird,463,4.684665
175236,The Da Vinci Code,828,4.679952
172364,The Catcher in the Rye,401,4.615960
197170,The Secret Life of Bees,704,4.558239
179343,The Five People You Meet in Heaven,392,4.543367
187414,The Lovely Bones: A Novel,1164,4.457045
727,1984,259,4.393822
182870,The Hitchhiker's Guide to the Galaxy,252,4.361111
161045,Stupid White Men ...and Other Sorry Excuses fo...,264,4.337121
195141,The Red Tent (Bestselling Backlist),668,4.326347
213071,"Tuesdays with Morrie: An Old Man, a Young Man,...",437,4.274600
123501,Nickel and Dimed: On (Not) Getting By in America,303,4.244224
61070,Fahrenheit 451,372,4.239247
71407,Girl with a Pearl Earring,486,4.197531
62081,Fast Food Nation: The Dark Side of the All-Ame...,285,4.133333
72927,Good in Bed,456,4.127193
129957,Outlander,262,4.087786
222878,Where the Heart Is (Oprah's Book Club (Paperba...,527,4.070209
148937,Seabiscuit: An American Legend,257,4.066148
168806,The Bean Trees,365,4.032877
103091,Life of Pi,597,4.015075
101002,Left Behind: A Novel of the Earth's Last Days ...,296,3.972973
173443,The Color Purple,289,3.972318
8101,ANGELA'S ASHES,253,3.964427
154258,Skipping Christmas,292,3.934932
180928,"The Golden Compass (His Dark Materials, Book 1)",302,3.927152
12160,American Gods,271,3.896679
209426,Timeline,512,3.857422
150884,Seven Up (A Stephanie Plum Novel),255,3.827451
76493,Hard Eight : A Stephanie Plum Novel (A Stephan...,252,3.821429
5439,A Prayer for Owen Meany,380,3.818421
13783,Angels &amp; Demons,616,3.788961
223339,White Oleander : A Novel (Oprah's Book Club),327,3.785933
202490,"The Vampire Lestat (Vampire Chronicles, Book II)",271,3.756458
162364,Suzanne's Diary for Nicholas,413,3.738499
112883,Me Talk Pretty One Day,426,3.727700
128390,One for the Money (Stephanie Plum Novels (Pape...,269,3.706320
224193,Wicked: The Life and Times of the Wicked Witch...,286,3.678322
20807,Bel Canto: A Novel,319,3.664577
37146,Confessions of a Shopaholic (Summer Display Op...,312,3.663462
115637,Misery,260,3.646154
193383,The Poisonwood Bible: A Novel,455,3.639560
57551,Empire Falls,368,3.635870

In [45]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_rating']]

In [46]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_rating
0,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,346,5.945087
2,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,380,5.884211
5,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,316,5.544304
9,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,501,5.177645
12,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,261,4.969349
13,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,519,4.938343
15,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,340,4.885294
24,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,463,4.684665
32,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,828,4.679952
38,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,401,4.615960
45,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,704,4.558239
51,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,392,4.543367
53,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1164,4.457045
54,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,259,4.393822
65,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,252,4.361111
74,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,264,4.337121
75,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,668,4.326347
76,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,437,4.274600
79,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,303,4.244224
81,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,372,4.239247
94,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,486,4.197531
95,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,285,4.133333
96,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,456,4.127193
98,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,262,4.087786
104,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,527,4.070209
105,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,257,4.066148
107,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,365,4.032877
110,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,597,4.015075
114,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,296,3.972973
116,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,289,3.972318
122,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,253,3.964427
124,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,292,3.934932
130,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,302,3.927152
138,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,271,3.896679
139,Timeline,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345417623.0...,512,3.857422
146,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,255,3.827451
148,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,252,3.821429
153,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,380,3.818421
155,Angels &amp; Demons,Dan Brown,http://images.amazon.com/images/P/0671027360.0...,616,3.788961
160,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,327,3.785933
161,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,271,3.756458
162,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,413,3.738499
166,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/0316776963.0...,426,3.727700
170,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,269,3.706320
171,Wicked: The Life and Times of the Wicked Witch...,Gregory Maguire,http://images.amazon.com/images/P/0060987103.0...,286,3.678322
172,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,319,3.664577
173,Confessions of a Shopaholic (Summer Display Op...,SOPHIE KINSELLA,http://images.amazon.com/images/P/0385335482.0...,312,3.663462
174,Misery,Stephen King,http://images.amazon.com/images/P/0451153553.0...,260,3.646154
182,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,455,3.639560
183,Empire Falls,Richard Russo,http://images.amazon.com/images/P/0375726403.0...,368,3.635870

In [47]:
# books
# rating- user id, book id, rating 
# data from these 2 
# user 1 user 2 user 3 user 4

# book1
# book2 
# book3
# book4 
# book5

# we will not be dealing with every book and every user, we will consider only those users who have rated min 200 books 
# we will consider only those books who has got at least 50 different people.

# Collaborative based filtering

In [86]:
x= rating_with_name.groupby('User-ID').count()['Book-Rating']>200
# This groups the data by userid and counts the number of book rating entries for each user. it then
# checks which users have rated more than 200 books, returning a boolean series. (true for users with more than 200 
# and false for others)

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 83643, dtype: bool

In [91]:
smart_people =x[x].index
# x[x].index: This selects the True entries from x (i.e., users with more than 200 ratings) 
#     and retrieves their indices (which are the User-IDs in this case).

In [92]:
smart_people

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            249111, 249628, 249862, 249894, 250184, 250405, 250764, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=737)

In [64]:
filtered_rating= rating_with_name[rating_with_name['User-ID'].isin(smart_people)]

In [95]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
941107,250764,440106575,0,HIDDEN FIRES,JANETTE RADCLIFFE,1978,Dell,http://images.amazon.com/images/P/0440106575.0...,http://images.amazon.com/images/P/0440106575.0...,http://images.amazon.com/images/P/0440106575.0...
941108,250764,451157516,0,"Cheyenne (Fortunes West, No 2)",A.R. Riefe,1988,New Amer Library (Mm),http://images.amazon.com/images/P/0451157516.0...,http://images.amazon.com/images/P/0451157516.0...,http://images.amazon.com/images/P/0451157516.0...
941109,250764,048623715X,0,Glamorous Movie Stars of the Thirties: Paper D...,Tom Tierney,1982,Dover Publications,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...
941110,250764,486256588,0,Schiaparelli Fashion Review: Paper Dolls in Fu...,Tom Tierney,1988,Dover Publications,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...
941111,250764,515069434,0,Lady Laughing Eyes (To Have and to Hold),Lee Damon,1984,Jove Books,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...

In [99]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50

In [100]:
y[y]

Book-Title
1984                                                                 True
1st to Die: A Novel                                                  True
2nd Chance                                                           True
4 Blondes                                                            True
A Bend in the Road                                                   True
                                                                     ...
Year of Wonders                                                      True
You Belong To Me                                                     True
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values    True
Zoya                                                                 True
\O\" Is for Outlaw"                                                  True
Name: Book-Rating, Length: 603, dtype: bool

In [101]:
famous_books =y[y].index

In [104]:
final_ratings =filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [105]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
56,278418,446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
58,3363,446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
59,7158,446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
62,11676,446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
67,23768,446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
937464,245963,380781506,0,Remember Me,Danice Allen,1996,Harper Mass Market Paperbacks (Mm),http://images.amazon.com/images/P/0380781506.0...,http://images.amazon.com/images/P/0380781506.0...,http://images.amazon.com/images/P/0380781506.0...
937465,246671,380781506,0,Remember Me,Danice Allen,1996,Harper Mass Market Paperbacks (Mm),http://images.amazon.com/images/P/0380781506.0...,http://images.amazon.com/images/P/0380781506.0...,http://images.amazon.com/images/P/0380781506.0...
938778,247429,073940086X,0,Mirror Image,Danielle Steel,0,Delacorte Press,http://images.amazon.com/images/P/073940086X.0...,http://images.amazon.com/images/P/073940086X.0...,http://images.amazon.com/images/P/073940086X.0...
939428,248718,031202164X,8,Ashes to Ashes,Mary Monica Pulver,1988,Horizon Book Promotions,http://images.amazon.com/images/P/031202164X.0...,http://images.amazon.com/images/P/031202164X.0...,http://images.amazon.com/images/P/031202164X.0...
940825,250405,399144781,0,Southern Cross,Patricia Daniels Cornwell,1999,Putnam Pub Group,http://images.amazon.com/images/P/0399144781.0...,http://images.amazon.com/images/P/0399144781.0...,http://images.amazon.com/images/P/0399144781.0...

In [108]:
pt =final_ratings.pivot_table(index ='Book-Title',columns= 'User-ID', values ='Book-Rating')

In [109]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,249111,249628,249862,249894,250184,250405,250764,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
pt.fillna(0, inplace = True)

In [111]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,249111,249628,249862,249894,250184,250405,250764,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(pt)

array([[1.        , 0.11013674, 0.0127091 , ..., 0.12447747, 0.07552261,
        0.04645965],
       [0.11013674, 1.        , 0.22459428, ..., 0.07780233, 0.1752651 ,
        0.12821608],
       [0.0127091 , 0.22459428, 1.        , ..., 0.04617038, 0.05001715,
        0.11450939],
       ...,
       [0.12447747, 0.07780233, 0.04617038, ..., 1.        , 0.07085128,
        0.02054493],
       [0.07552261, 0.1752651 , 0.05001715, ..., 0.07085128, 1.        ,
        0.11104108],
       [0.04645965, 0.12821608, 0.11450939, ..., 0.02054493, 0.11104108,
        1.        ]])

In [114]:
cosine_similarity(pt).shape

(603, 603)

In [115]:
similarity_score = cosine_similarity(pt)

In [116]:
similarity_score

array([[1.        , 0.11013674, 0.0127091 , ..., 0.12447747, 0.07552261,
        0.04645965],
       [0.11013674, 1.        , 0.22459428, ..., 0.07780233, 0.1752651 ,
        0.12821608],
       [0.0127091 , 0.22459428, 1.        , ..., 0.04617038, 0.05001715,
        0.11450939],
       ...,
       [0.12447747, 0.07780233, 0.04617038, ..., 1.        , 0.07085128,
        0.02054493],
       [0.07552261, 0.1752651 , 0.05001715, ..., 0.07085128, 1.        ,
        0.11104108],
       [0.04645965, 0.12821608, 0.11450939, ..., 0.02054493, 0.11104108,
        1.        ]])

In [117]:
np.where(pt.index== 'Zoya')[0][0]

601

In [128]:
def recommend(book_name):
#     fetch index
   index = np.where(pt.index== book_name)[0][0]
   distances = similarity_score[index]
   similar_items = sorted(list(enumerate(similarity_score[index])),key= lambda x:x[1], reverse = True)[1:6]
   for i in similar_items :
    print(pt.index[i[0]])

In [125]:
sorted(list(enumerate(similarity_score[0])),key= lambda x:x[1], reverse = True)[1:6]

[(41, 0.27779439320159416),
 (70, 0.2660586000369668),
 (541, 0.2506295364129756),
 (459, 0.23786512783485833),
 (147, 0.234784541598818)]

In [130]:
pt.index[45]

'Artemis Fowl (Artemis Fowl, Book 1)'

In [129]:
recommend('1984')

Animal Farm
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Handmaid's Tale
Fahrenheit 451

In [131]:
recommend('Message in a Bottle')

Nightmares &amp; Dreamscapes
Nights in Rodanthe
A Walk to Remember
The Mulberry Tree
All I Really Need to Know